### ISSUE TITLE
Upvote/Downvote Feature

### ISSUE THREAD

**Issue by kart2k15** [briandoyle89/CSE442_MVP#39]
Since we don't want students using this website to violate academic integrity. We need a way to ensure the quality & **content** of the documents uploaded to our database.  Hence each user should have an option to upvote/downvote on an uploaded document.  If it reaches a certain no. of down-votes we remove it from our database.

**Comment by MirRaonaq** [comment]
Hey @kart2k15 , I seem to have finished the upvote/ downvote feature. Before I push it to my forked repo. Can I meet up with you after the Mondays lecture to show you my work?

**Comment by kart2k15** [comment]
Yeah man, today there is no class I assume! So you want to meet up then?

**Comment by kart2k15** [comment]
Word I’ll see you at Baldy at 4 today.

**Comment by kart2k15** [comment]
yoo, I am here

**Comment by MirRaonaq** [comment]
Hey, it has been completed & has been reviewed as per the requirements. @kart2k15

**Comment by kart2k15** [comment]
It’s done, thank you! @MirRaonaq
