### ISSUE TITLE
Keep track of number of downloads vs uploads

### ISSUE THREAD

**Issue by briandoyle89** [briandoyle89/CSE442_MVP#42]
In the user model, we have two ints for "submissions" and "downloads."

When someone uploads or downloads a file, we would like to keep track of it.  We want to encourage users to upload files and not just download them, so eventually we will keep track of a ratio that makes users need to upload files to continue downloading them.

**Comment by LameLemon** [comment]
Hello, I'm assigned to your issue for the collaboration phase. I went through the documentation in the wiki but have not fully setup the environment yet. I have found the user model in models.py and seen that the default upload and download is set to 0. In the issue you said something about maintaining a ration, I wanted to know what you wanted me to do within the user class. Thank you.

**Comment by jwreimer** [comment]
#81
