### ISSUE TITLE
Bug reporting 

### ISSUE THREAD

**Issue by xinyuche** [briandoyle89/CSE442_MVP#46]
When i were trying to upload the document to the cse442 course in your website, there are something happened. We can select the course, but there is no correct course name for cse442. Instead, it give me a course object 1 and course object 2, which makes me so confused. After I upload the document, I cannot see any documents appeared on either cse 116 and cse 442. One more think, when you pressed the "UB_Liberator", shouldn't it go back to the main page again?

**Comment by jwreimer** [comment]
Thank you, also has been reported #45

**Comment by jwreimer** [comment]
Has been finished by the same code that fixed #45
