### ISSUE TITLE
Major Bug: unable to register

### ISSUE THREAD

**Issue by alexwucs** [briandoyle89/CSE442_MVP#50]
Hi team, I've noticed that I couldn't register my account and this happens. https://ubliberator3.pythonanywhere.com/check_register

[ValueError at :check_register.pdf](https://github.com/briandoyle89/CSE442_MVP/files/1858333/ValueError.at.check_register.pdf)

Thank you.

**Comment by jwreimer** [comment]
Most edge cases have been tested, still examining this issue, is there any way you could provide us with more information regarding this bug? (Although I do recognize it was a little while ago)

**Comment by jwreimer** [comment]
After testing differing potentially invalid character combinations, character counts for both username and password, email combinations etc, and attempting strange edge cases, I have yet to find a cause for this error. I will keep my eye out and keep testing moving forward, hopefully another user will be able to recreate the results and will be able to allow us a little bit more information into the cause.

**Comment by jwreimer** [comment]
Bug possibly still remaining, affecting a trivial amount of users with unknown cases. Can be reopened if another user reports a similar experience and has more data to provide.
