### ISSUE TITLE
[Minor Bug] Sign up and Log in button don't work

### ISSUE THREAD

**Issue by LameLemon** [briandoyle89/CSE442_MVP#60]
After logging, there still appears to be a log in button on the top right hand side of the screen, this button however does not do anything. Beside that there is also a sign up button which does not do anything yet. Both these buttons should not be needed if the user has successfully signed in. 

![out](https://user-images.githubusercontent.com/35942108/38597232-6d2fece4-3d24-11e8-92ac-a6fa26641d72.gif)

**Comment by briandoyle89** [comment]
Fixed.
