### ISSUE TITLE
[Minor Bug] About Page unreachable 

### ISSUE THREAD

**Issue by linlinlin3** [briandoyle89/CSE442_MVP#62]
When on the any page, clicking the ”About Us" button in the menu bar leads to `TemplateSyntaxError at /aboutus`. Additionally, under "UB_Liberator" the image does not display and only says "Cinque Terre". Both of these bugs are demonstrated in the image below.
![2](https://user-images.githubusercontent.com/36248334/38690175-7bf6fede-3e4b-11e8-9565-93f835f04b4b.PNG)
![1](https://user-images.githubusercontent.com/36248334/38690178-7f3e2d74-3e4b-11e8-8b42-f9b4bf3f8501.PNG)

**Comment by briandoyle89** [comment]
Fixed.
