### ISSUE TITLE
Vulnerabilities

### ISSUE THREAD

**Issue by silentaim** [briandoyle89/CSE442_MVP#71]
1. All your links are directly exposed, aka I can do this: 
https://ubliberator3.pythonanywhere.com/download/documents/10-VersionControl_Vw2c3o6.pptx

2. You have a file size limit, but you can still submit the file and transfer the data. Easy to crash the site.

3. All your pages are exposed:

![image](https://user-images.githubusercontent.com/8918512/38710647-6f1dbf9c-3e8f-11e8-81c9-ca26c3bc8619.png)

4. Your admin panel can be brute forced, consider setting an htaccess

**Comment by jwreimer** [comment]
#77 , Added regex...
