### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by z28980361** [briandoyle89/CSE442_MVP#80]
Hi guys, I am one of your alpha testers, and I found an bug on registration page.
When I am trying to register with 
email: 123@email.com (fake email, email confirmation is probably also something that you guys need to consider)
username: test<!--
password: 1
It registered successfully, but when I try to login with this account, nothing happened. I thing you guys probably did not escape html completely. Besides, I can register with those information infinite times without getting any username duplication warning(that's how I reproduce this bug).
The gif below should give you a better understanding of this bug.
![alphatest](https://user-images.githubusercontent.com/22279235/38834624-ffbd3564-4196-11e8-805d-dcedb1e32ecc.gif)

**Comment by briandoyle89** [comment]
Interesting, will need to double check the regex expressions.

**Comment by jwreimer** [comment]
#77
