### ISSUE TITLE
Bug: Search Button Not Always Working

### ISSUE THREAD

**Issue by aforthma** [briandoyle89/CSE442_MVP#86]
Looks like there is a general issue of content overlapping each other in this site. From my attempts at using the search box and some troubleshooting, it seems the overlapping is preventing the Search button from being used at times.

Initially, which in the CSE 115 section, I tried searching for a file by name. After putting the name in the text box, I try to click the button once, then a number of times, with no result. Pressing Enter within the text box works and brings up the file I entered in. Some additional attempts, including starting at the home page, shows the button does work at times. Clicking it here, I notice it depresses and brings me to an error page for not putting anything in the box. Trying on CSE 115 again as previously described I go back to the button not working, including it not depressing at all. Thinking maybe there's some overlapping issue, I tried maximizing the window and trying again. This time the button works. 

Overlapping is showing up in other areas, especially the section to upload a document. I'm using Google Chrome on a Windows 10 machine and have the window taking up the right half side of the screen at the times when the overlapping shows up.

**Comment by briandoyle89** [comment]
Thanks for pointing this out - very weird how the hit box seems to move as the screen is resized.

**Comment by jwreimer** [comment]
#83 
Issues with search bar seem to have been solved, if any more occurences come up, we shall reopen this issue and attempt to address. Any remaining slight overlap can be counted as a trivial visual bug, tends to occur with certain sizes of windows.
